
server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: springboot2-essentials

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2 Essentials
  website: https://www.linkedin.com/in/tuliomuller/
  github: https://github.com/mmtulio/springboot2-essentials